(cl:defpackage robotnik_elevator_interface_msgs-srv
  (:use )
  (:export
   "GOTOFLOOR"
   "<GOTOFLOOR-REQUEST>"
   "GOTOFLOOR-REQUEST"
   "<GOTOFLOOR-RESPONSE>"
   "GOTOFLOOR-RESPONSE"
   "SETDOORSTATE"
   "<SETDOORSTATE-REQUEST>"
   "SETDOORSTATE-REQUEST"
   "<SETDOORSTATE-RESPONSE>"
   "SETDOORSTATE-RESPONSE"
   "SETELEVATORCONTROL"
   "<SETELEVATORCONTROL-REQUEST>"
   "SETELEVATORCONTROL-REQUEST"
   "<SETELEVATORCONTROL-RESPONSE>"
   "SETELEVATORCONTROL-RESPONSE"
  ))

