set(interbotix_xsarm_diagnostic_tool_MESSAGE_FILES "/home/xinyao/SAR_ROS/catkin_ws/src/trossen/interbotix_ros_manipulators/interbotix_ros_xsarms/examples/interbotix_xsarm_diagnostic_tool/msg/JointTemps.msg")
set(interbotix_xsarm_diagnostic_tool_SERVICE_FILES "")
