// Generated by gencpp from file robotnik_elevator_interface_msgs/GoToFloor.msg
// DO NOT EDIT!


#ifndef ROBOTNIK_ELEVATOR_INTERFACE_MSGS_MESSAGE_GOTOFLOOR_H
#define ROBOTNIK_ELEVATOR_INTERFACE_MSGS_MESSAGE_GOTOFLOOR_H

#include <ros/service_traits.h>


#include <robotnik_elevator_interface_msgs/GoToFloorRequest.h>
#include <robotnik_elevator_interface_msgs/GoToFloorResponse.h>


namespace robotnik_elevator_interface_msgs
{

struct GoToFloor
{

typedef GoToFloorRequest Request;
typedef GoToFloorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GoToFloor
} // namespace robotnik_elevator_interface_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotnik_elevator_interface_msgs::GoToFloor > {
  static const char* value()
  {
    return "597b9b64f569298d176a3be74c2f6432";
  }

  static const char* value(const ::robotnik_elevator_interface_msgs::GoToFloor&) { return value(); }
};

template<>
struct DataType< ::robotnik_elevator_interface_msgs::GoToFloor > {
  static const char* value()
  {
    return "robotnik_elevator_interface_msgs/GoToFloor";
  }

  static const char* value(const ::robotnik_elevator_interface_msgs::GoToFloor&) { return value(); }
};


// service_traits::MD5Sum< ::robotnik_elevator_interface_msgs::GoToFloorRequest> should match
// service_traits::MD5Sum< ::robotnik_elevator_interface_msgs::GoToFloor >
template<>
struct MD5Sum< ::robotnik_elevator_interface_msgs::GoToFloorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotnik_elevator_interface_msgs::GoToFloor >::value();
  }
  static const char* value(const ::robotnik_elevator_interface_msgs::GoToFloorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotnik_elevator_interface_msgs::GoToFloorRequest> should match
// service_traits::DataType< ::robotnik_elevator_interface_msgs::GoToFloor >
template<>
struct DataType< ::robotnik_elevator_interface_msgs::GoToFloorRequest>
{
  static const char* value()
  {
    return DataType< ::robotnik_elevator_interface_msgs::GoToFloor >::value();
  }
  static const char* value(const ::robotnik_elevator_interface_msgs::GoToFloorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotnik_elevator_interface_msgs::GoToFloorResponse> should match
// service_traits::MD5Sum< ::robotnik_elevator_interface_msgs::GoToFloor >
template<>
struct MD5Sum< ::robotnik_elevator_interface_msgs::GoToFloorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotnik_elevator_interface_msgs::GoToFloor >::value();
  }
  static const char* value(const ::robotnik_elevator_interface_msgs::GoToFloorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotnik_elevator_interface_msgs::GoToFloorResponse> should match
// service_traits::DataType< ::robotnik_elevator_interface_msgs::GoToFloor >
template<>
struct DataType< ::robotnik_elevator_interface_msgs::GoToFloorResponse>
{
  static const char* value()
  {
    return DataType< ::robotnik_elevator_interface_msgs::GoToFloor >::value();
  }
  static const char* value(const ::robotnik_elevator_interface_msgs::GoToFloorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTNIK_ELEVATOR_INTERFACE_MSGS_MESSAGE_GOTOFLOOR_H
