// Generated by gencpp from file robotnik_elevator_interface_msgs/SetDoorState.msg
// DO NOT EDIT!


#ifndef ROBOTNIK_ELEVATOR_INTERFACE_MSGS_MESSAGE_SETDOORSTATE_H
#define ROBOTNIK_ELEVATOR_INTERFACE_MSGS_MESSAGE_SETDOORSTATE_H

#include <ros/service_traits.h>


#include <robotnik_elevator_interface_msgs/SetDoorStateRequest.h>
#include <robotnik_elevator_interface_msgs/SetDoorStateResponse.h>


namespace robotnik_elevator_interface_msgs
{

struct SetDoorState
{

typedef SetDoorStateRequest Request;
typedef SetDoorStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetDoorState
} // namespace robotnik_elevator_interface_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotnik_elevator_interface_msgs::SetDoorState > {
  static const char* value()
  {
    return "d23ce984296255998e5bcc26595a09b8";
  }

  static const char* value(const ::robotnik_elevator_interface_msgs::SetDoorState&) { return value(); }
};

template<>
struct DataType< ::robotnik_elevator_interface_msgs::SetDoorState > {
  static const char* value()
  {
    return "robotnik_elevator_interface_msgs/SetDoorState";
  }

  static const char* value(const ::robotnik_elevator_interface_msgs::SetDoorState&) { return value(); }
};


// service_traits::MD5Sum< ::robotnik_elevator_interface_msgs::SetDoorStateRequest> should match
// service_traits::MD5Sum< ::robotnik_elevator_interface_msgs::SetDoorState >
template<>
struct MD5Sum< ::robotnik_elevator_interface_msgs::SetDoorStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotnik_elevator_interface_msgs::SetDoorState >::value();
  }
  static const char* value(const ::robotnik_elevator_interface_msgs::SetDoorStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotnik_elevator_interface_msgs::SetDoorStateRequest> should match
// service_traits::DataType< ::robotnik_elevator_interface_msgs::SetDoorState >
template<>
struct DataType< ::robotnik_elevator_interface_msgs::SetDoorStateRequest>
{
  static const char* value()
  {
    return DataType< ::robotnik_elevator_interface_msgs::SetDoorState >::value();
  }
  static const char* value(const ::robotnik_elevator_interface_msgs::SetDoorStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotnik_elevator_interface_msgs::SetDoorStateResponse> should match
// service_traits::MD5Sum< ::robotnik_elevator_interface_msgs::SetDoorState >
template<>
struct MD5Sum< ::robotnik_elevator_interface_msgs::SetDoorStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotnik_elevator_interface_msgs::SetDoorState >::value();
  }
  static const char* value(const ::robotnik_elevator_interface_msgs::SetDoorStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotnik_elevator_interface_msgs::SetDoorStateResponse> should match
// service_traits::DataType< ::robotnik_elevator_interface_msgs::SetDoorState >
template<>
struct DataType< ::robotnik_elevator_interface_msgs::SetDoorStateResponse>
{
  static const char* value()
  {
    return DataType< ::robotnik_elevator_interface_msgs::SetDoorState >::value();
  }
  static const char* value(const ::robotnik_elevator_interface_msgs::SetDoorStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTNIK_ELEVATOR_INTERFACE_MSGS_MESSAGE_SETDOORSTATE_H
