// Generated by gencpp from file robotnik_elevator_interface_msgs/SetDoorStateRequest.msg
// DO NOT EDIT!


#ifndef ROBOTNIK_ELEVATOR_INTERFACE_MSGS_MESSAGE_SETDOORSTATEREQUEST_H
#define ROBOTNIK_ELEVATOR_INTERFACE_MSGS_MESSAGE_SETDOORSTATEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotnik_elevator_interface_msgs
{
template <class ContainerAllocator>
struct SetDoorStateRequest_
{
  typedef SetDoorStateRequest_<ContainerAllocator> Type;

  SetDoorStateRequest_()
    : state()
    , control_token()  {
    }
  SetDoorStateRequest_(const ContainerAllocator& _alloc)
    : state(_alloc)
    , control_token(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _state_type;
  _state_type state;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _control_token_type;
  _control_token_type control_token;





  typedef boost::shared_ptr< ::robotnik_elevator_interface_msgs::SetDoorStateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotnik_elevator_interface_msgs::SetDoorStateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetDoorStateRequest_

typedef ::robotnik_elevator_interface_msgs::SetDoorStateRequest_<std::allocator<void> > SetDoorStateRequest;

typedef boost::shared_ptr< ::robotnik_elevator_interface_msgs::SetDoorStateRequest > SetDoorStateRequestPtr;
typedef boost::shared_ptr< ::robotnik_elevator_interface_msgs::SetDoorStateRequest const> SetDoorStateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotnik_elevator_interface_msgs::SetDoorStateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotnik_elevator_interface_msgs::SetDoorStateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robotnik_elevator_interface_msgs::SetDoorStateRequest_<ContainerAllocator1> & lhs, const ::robotnik_elevator_interface_msgs::SetDoorStateRequest_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state &&
    lhs.control_token == rhs.control_token;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robotnik_elevator_interface_msgs::SetDoorStateRequest_<ContainerAllocator1> & lhs, const ::robotnik_elevator_interface_msgs::SetDoorStateRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robotnik_elevator_interface_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robotnik_elevator_interface_msgs::SetDoorStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotnik_elevator_interface_msgs::SetDoorStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotnik_elevator_interface_msgs::SetDoorStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotnik_elevator_interface_msgs::SetDoorStateRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotnik_elevator_interface_msgs::SetDoorStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotnik_elevator_interface_msgs::SetDoorStateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotnik_elevator_interface_msgs::SetDoorStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f904af2c4102d2a084b5bf7cfcd77f89";
  }

  static const char* value(const ::robotnik_elevator_interface_msgs::SetDoorStateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf904af2c4102d2a0ULL;
  static const uint64_t static_value2 = 0x84b5bf7cfcd77f89ULL;
};

template<class ContainerAllocator>
struct DataType< ::robotnik_elevator_interface_msgs::SetDoorStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotnik_elevator_interface_msgs/SetDoorStateRequest";
  }

  static const char* value(const ::robotnik_elevator_interface_msgs::SetDoorStateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotnik_elevator_interface_msgs::SetDoorStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# See ElevatorState (open,close)\n"
"string state\n"
"# unique control token to avoid controlling the elevator from external agents\n"
"string control_token\n"
;
  }

  static const char* value(const ::robotnik_elevator_interface_msgs::SetDoorStateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotnik_elevator_interface_msgs::SetDoorStateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
      stream.next(m.control_token);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetDoorStateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotnik_elevator_interface_msgs::SetDoorStateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotnik_elevator_interface_msgs::SetDoorStateRequest_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.state);
    s << indent << "control_token: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.control_token);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTNIK_ELEVATOR_INTERFACE_MSGS_MESSAGE_SETDOORSTATEREQUEST_H
