// Generated by gencpp from file interbotix_xs_sdk/Reboot.msg
// DO NOT EDIT!


#ifndef INTERBOTIX_XS_SDK_MESSAGE_REBOOT_H
#define INTERBOTIX_XS_SDK_MESSAGE_REBOOT_H

#include <ros/service_traits.h>


#include <interbotix_xs_sdk/RebootRequest.h>
#include <interbotix_xs_sdk/RebootResponse.h>


namespace interbotix_xs_sdk
{

struct Reboot
{

typedef RebootRequest Request;
typedef RebootResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Reboot
} // namespace interbotix_xs_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::interbotix_xs_sdk::Reboot > {
  static const char* value()
  {
    return "229067e7bfb48bf403b702d5f7f1ee93";
  }

  static const char* value(const ::interbotix_xs_sdk::Reboot&) { return value(); }
};

template<>
struct DataType< ::interbotix_xs_sdk::Reboot > {
  static const char* value()
  {
    return "interbotix_xs_sdk/Reboot";
  }

  static const char* value(const ::interbotix_xs_sdk::Reboot&) { return value(); }
};


// service_traits::MD5Sum< ::interbotix_xs_sdk::RebootRequest> should match
// service_traits::MD5Sum< ::interbotix_xs_sdk::Reboot >
template<>
struct MD5Sum< ::interbotix_xs_sdk::RebootRequest>
{
  static const char* value()
  {
    return MD5Sum< ::interbotix_xs_sdk::Reboot >::value();
  }
  static const char* value(const ::interbotix_xs_sdk::RebootRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::interbotix_xs_sdk::RebootRequest> should match
// service_traits::DataType< ::interbotix_xs_sdk::Reboot >
template<>
struct DataType< ::interbotix_xs_sdk::RebootRequest>
{
  static const char* value()
  {
    return DataType< ::interbotix_xs_sdk::Reboot >::value();
  }
  static const char* value(const ::interbotix_xs_sdk::RebootRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::interbotix_xs_sdk::RebootResponse> should match
// service_traits::MD5Sum< ::interbotix_xs_sdk::Reboot >
template<>
struct MD5Sum< ::interbotix_xs_sdk::RebootResponse>
{
  static const char* value()
  {
    return MD5Sum< ::interbotix_xs_sdk::Reboot >::value();
  }
  static const char* value(const ::interbotix_xs_sdk::RebootResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::interbotix_xs_sdk::RebootResponse> should match
// service_traits::DataType< ::interbotix_xs_sdk::Reboot >
template<>
struct DataType< ::interbotix_xs_sdk::RebootResponse>
{
  static const char* value()
  {
    return DataType< ::interbotix_xs_sdk::Reboot >::value();
  }
  static const char* value(const ::interbotix_xs_sdk::RebootResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INTERBOTIX_XS_SDK_MESSAGE_REBOOT_H
