// Generated by gencpp from file interbotix_xs_sdk/RobotInfo.msg
// DO NOT EDIT!


#ifndef INTERBOTIX_XS_SDK_MESSAGE_ROBOTINFO_H
#define INTERBOTIX_XS_SDK_MESSAGE_ROBOTINFO_H

#include <ros/service_traits.h>


#include <interbotix_xs_sdk/RobotInfoRequest.h>
#include <interbotix_xs_sdk/RobotInfoResponse.h>


namespace interbotix_xs_sdk
{

struct RobotInfo
{

typedef RobotInfoRequest Request;
typedef RobotInfoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RobotInfo
} // namespace interbotix_xs_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::interbotix_xs_sdk::RobotInfo > {
  static const char* value()
  {
    return "7a389566d99903aa71839d0052c9a055";
  }

  static const char* value(const ::interbotix_xs_sdk::RobotInfo&) { return value(); }
};

template<>
struct DataType< ::interbotix_xs_sdk::RobotInfo > {
  static const char* value()
  {
    return "interbotix_xs_sdk/RobotInfo";
  }

  static const char* value(const ::interbotix_xs_sdk::RobotInfo&) { return value(); }
};


// service_traits::MD5Sum< ::interbotix_xs_sdk::RobotInfoRequest> should match
// service_traits::MD5Sum< ::interbotix_xs_sdk::RobotInfo >
template<>
struct MD5Sum< ::interbotix_xs_sdk::RobotInfoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::interbotix_xs_sdk::RobotInfo >::value();
  }
  static const char* value(const ::interbotix_xs_sdk::RobotInfoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::interbotix_xs_sdk::RobotInfoRequest> should match
// service_traits::DataType< ::interbotix_xs_sdk::RobotInfo >
template<>
struct DataType< ::interbotix_xs_sdk::RobotInfoRequest>
{
  static const char* value()
  {
    return DataType< ::interbotix_xs_sdk::RobotInfo >::value();
  }
  static const char* value(const ::interbotix_xs_sdk::RobotInfoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::interbotix_xs_sdk::RobotInfoResponse> should match
// service_traits::MD5Sum< ::interbotix_xs_sdk::RobotInfo >
template<>
struct MD5Sum< ::interbotix_xs_sdk::RobotInfoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::interbotix_xs_sdk::RobotInfo >::value();
  }
  static const char* value(const ::interbotix_xs_sdk::RobotInfoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::interbotix_xs_sdk::RobotInfoResponse> should match
// service_traits::DataType< ::interbotix_xs_sdk::RobotInfo >
template<>
struct DataType< ::interbotix_xs_sdk::RobotInfoResponse>
{
  static const char* value()
  {
    return DataType< ::interbotix_xs_sdk::RobotInfo >::value();
  }
  static const char* value(const ::interbotix_xs_sdk::RobotInfoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INTERBOTIX_XS_SDK_MESSAGE_ROBOTINFO_H
