// Generated by gencpp from file interbotix_xs_sdk/TorqueEnable.msg
// DO NOT EDIT!


#ifndef INTERBOTIX_XS_SDK_MESSAGE_TORQUEENABLE_H
#define INTERBOTIX_XS_SDK_MESSAGE_TORQUEENABLE_H

#include <ros/service_traits.h>


#include <interbotix_xs_sdk/TorqueEnableRequest.h>
#include <interbotix_xs_sdk/TorqueEnableResponse.h>


namespace interbotix_xs_sdk
{

struct TorqueEnable
{

typedef TorqueEnableRequest Request;
typedef TorqueEnableResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TorqueEnable
} // namespace interbotix_xs_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::interbotix_xs_sdk::TorqueEnable > {
  static const char* value()
  {
    return "023452ade9f3d4979c75bd4e0d60f0c9";
  }

  static const char* value(const ::interbotix_xs_sdk::TorqueEnable&) { return value(); }
};

template<>
struct DataType< ::interbotix_xs_sdk::TorqueEnable > {
  static const char* value()
  {
    return "interbotix_xs_sdk/TorqueEnable";
  }

  static const char* value(const ::interbotix_xs_sdk::TorqueEnable&) { return value(); }
};


// service_traits::MD5Sum< ::interbotix_xs_sdk::TorqueEnableRequest> should match
// service_traits::MD5Sum< ::interbotix_xs_sdk::TorqueEnable >
template<>
struct MD5Sum< ::interbotix_xs_sdk::TorqueEnableRequest>
{
  static const char* value()
  {
    return MD5Sum< ::interbotix_xs_sdk::TorqueEnable >::value();
  }
  static const char* value(const ::interbotix_xs_sdk::TorqueEnableRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::interbotix_xs_sdk::TorqueEnableRequest> should match
// service_traits::DataType< ::interbotix_xs_sdk::TorqueEnable >
template<>
struct DataType< ::interbotix_xs_sdk::TorqueEnableRequest>
{
  static const char* value()
  {
    return DataType< ::interbotix_xs_sdk::TorqueEnable >::value();
  }
  static const char* value(const ::interbotix_xs_sdk::TorqueEnableRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::interbotix_xs_sdk::TorqueEnableResponse> should match
// service_traits::MD5Sum< ::interbotix_xs_sdk::TorqueEnable >
template<>
struct MD5Sum< ::interbotix_xs_sdk::TorqueEnableResponse>
{
  static const char* value()
  {
    return MD5Sum< ::interbotix_xs_sdk::TorqueEnable >::value();
  }
  static const char* value(const ::interbotix_xs_sdk::TorqueEnableResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::interbotix_xs_sdk::TorqueEnableResponse> should match
// service_traits::DataType< ::interbotix_xs_sdk::TorqueEnable >
template<>
struct DataType< ::interbotix_xs_sdk::TorqueEnableResponse>
{
  static const char* value()
  {
    return DataType< ::interbotix_xs_sdk::TorqueEnable >::value();
  }
  static const char* value(const ::interbotix_xs_sdk::TorqueEnableResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INTERBOTIX_XS_SDK_MESSAGE_TORQUEENABLE_H
