// Generated by gencpp from file irlab_point_cloud_filtering/PointCloudFilteringResponse.msg
// DO NOT EDIT!


#ifndef IRLAB_POINT_CLOUD_FILTERING_MESSAGE_POINTCLOUDFILTERINGRESPONSE_H
#define IRLAB_POINT_CLOUD_FILTERING_MESSAGE_POINTCLOUDFILTERINGRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace irlab_point_cloud_filtering
{
template <class ContainerAllocator>
struct PointCloudFilteringResponse_
{
  typedef PointCloudFilteringResponse_<ContainerAllocator> Type;

  PointCloudFilteringResponse_()
    {
    }
  PointCloudFilteringResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::irlab_point_cloud_filtering::PointCloudFilteringResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::irlab_point_cloud_filtering::PointCloudFilteringResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PointCloudFilteringResponse_

typedef ::irlab_point_cloud_filtering::PointCloudFilteringResponse_<std::allocator<void> > PointCloudFilteringResponse;

typedef boost::shared_ptr< ::irlab_point_cloud_filtering::PointCloudFilteringResponse > PointCloudFilteringResponsePtr;
typedef boost::shared_ptr< ::irlab_point_cloud_filtering::PointCloudFilteringResponse const> PointCloudFilteringResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::irlab_point_cloud_filtering::PointCloudFilteringResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::irlab_point_cloud_filtering::PointCloudFilteringResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace irlab_point_cloud_filtering

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::irlab_point_cloud_filtering::PointCloudFilteringResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::irlab_point_cloud_filtering::PointCloudFilteringResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::irlab_point_cloud_filtering::PointCloudFilteringResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::irlab_point_cloud_filtering::PointCloudFilteringResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::irlab_point_cloud_filtering::PointCloudFilteringResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::irlab_point_cloud_filtering::PointCloudFilteringResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::irlab_point_cloud_filtering::PointCloudFilteringResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::irlab_point_cloud_filtering::PointCloudFilteringResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::irlab_point_cloud_filtering::PointCloudFilteringResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "irlab_point_cloud_filtering/PointCloudFilteringResponse";
  }

  static const char* value(const ::irlab_point_cloud_filtering::PointCloudFilteringResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::irlab_point_cloud_filtering::PointCloudFilteringResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::irlab_point_cloud_filtering::PointCloudFilteringResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::irlab_point_cloud_filtering::PointCloudFilteringResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PointCloudFilteringResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::irlab_point_cloud_filtering::PointCloudFilteringResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::irlab_point_cloud_filtering::PointCloudFilteringResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // IRLAB_POINT_CLOUD_FILTERING_MESSAGE_POINTCLOUDFILTERINGRESPONSE_H
