// Generated by gencpp from file irlab_point_cloud_filtering/PointCloudFiltering.msg
// DO NOT EDIT!


#ifndef IRLAB_POINT_CLOUD_FILTERING_MESSAGE_POINTCLOUDFILTERING_H
#define IRLAB_POINT_CLOUD_FILTERING_MESSAGE_POINTCLOUDFILTERING_H

#include <ros/service_traits.h>


#include <irlab_point_cloud_filtering/PointCloudFilteringRequest.h>
#include <irlab_point_cloud_filtering/PointCloudFilteringResponse.h>


namespace irlab_point_cloud_filtering
{

struct PointCloudFiltering
{

typedef PointCloudFilteringRequest Request;
typedef PointCloudFilteringResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PointCloudFiltering
} // namespace irlab_point_cloud_filtering


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::irlab_point_cloud_filtering::PointCloudFiltering > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::irlab_point_cloud_filtering::PointCloudFiltering&) { return value(); }
};

template<>
struct DataType< ::irlab_point_cloud_filtering::PointCloudFiltering > {
  static const char* value()
  {
    return "irlab_point_cloud_filtering/PointCloudFiltering";
  }

  static const char* value(const ::irlab_point_cloud_filtering::PointCloudFiltering&) { return value(); }
};


// service_traits::MD5Sum< ::irlab_point_cloud_filtering::PointCloudFilteringRequest> should match
// service_traits::MD5Sum< ::irlab_point_cloud_filtering::PointCloudFiltering >
template<>
struct MD5Sum< ::irlab_point_cloud_filtering::PointCloudFilteringRequest>
{
  static const char* value()
  {
    return MD5Sum< ::irlab_point_cloud_filtering::PointCloudFiltering >::value();
  }
  static const char* value(const ::irlab_point_cloud_filtering::PointCloudFilteringRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::irlab_point_cloud_filtering::PointCloudFilteringRequest> should match
// service_traits::DataType< ::irlab_point_cloud_filtering::PointCloudFiltering >
template<>
struct DataType< ::irlab_point_cloud_filtering::PointCloudFilteringRequest>
{
  static const char* value()
  {
    return DataType< ::irlab_point_cloud_filtering::PointCloudFiltering >::value();
  }
  static const char* value(const ::irlab_point_cloud_filtering::PointCloudFilteringRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::irlab_point_cloud_filtering::PointCloudFilteringResponse> should match
// service_traits::MD5Sum< ::irlab_point_cloud_filtering::PointCloudFiltering >
template<>
struct MD5Sum< ::irlab_point_cloud_filtering::PointCloudFilteringResponse>
{
  static const char* value()
  {
    return MD5Sum< ::irlab_point_cloud_filtering::PointCloudFiltering >::value();
  }
  static const char* value(const ::irlab_point_cloud_filtering::PointCloudFilteringResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::irlab_point_cloud_filtering::PointCloudFilteringResponse> should match
// service_traits::DataType< ::irlab_point_cloud_filtering::PointCloudFiltering >
template<>
struct DataType< ::irlab_point_cloud_filtering::PointCloudFilteringResponse>
{
  static const char* value()
  {
    return DataType< ::irlab_point_cloud_filtering::PointCloudFiltering >::value();
  }
  static const char* value(const ::irlab_point_cloud_filtering::PointCloudFilteringResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IRLAB_POINT_CLOUD_FILTERING_MESSAGE_POINTCLOUDFILTERING_H
