# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from robotnik_msgs/MotorReferenceValue.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class MotorReferenceValue(genpy.Message):
  _md5sum = "bee092bed901770c06bbd09306ce8598"
  _type = "robotnik_msgs/MotorReferenceValue"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 target_value
int32 target_ref
float32 actual_value
int32 actual_ref
float32 spin
float32 offset"""
  __slots__ = ['target_value','target_ref','actual_value','actual_ref','spin','offset']
  _slot_types = ['float32','int32','float32','int32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       target_value,target_ref,actual_value,actual_ref,spin,offset

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MotorReferenceValue, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.target_value is None:
        self.target_value = 0.
      if self.target_ref is None:
        self.target_ref = 0
      if self.actual_value is None:
        self.actual_value = 0.
      if self.actual_ref is None:
        self.actual_ref = 0
      if self.spin is None:
        self.spin = 0.
      if self.offset is None:
        self.offset = 0.
    else:
      self.target_value = 0.
      self.target_ref = 0
      self.actual_value = 0.
      self.actual_ref = 0
      self.spin = 0.
      self.offset = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_fifi2f().pack(_x.target_value, _x.target_ref, _x.actual_value, _x.actual_ref, _x.spin, _x.offset))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.target_value, _x.target_ref, _x.actual_value, _x.actual_ref, _x.spin, _x.offset,) = _get_struct_fifi2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_fifi2f().pack(_x.target_value, _x.target_ref, _x.actual_value, _x.actual_ref, _x.spin, _x.offset))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.target_value, _x.target_ref, _x.actual_value, _x.actual_ref, _x.spin, _x.offset,) = _get_struct_fifi2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_fifi2f = None
def _get_struct_fifi2f():
    global _struct_fifi2f
    if _struct_fifi2f is None:
        _struct_fifi2f = struct.Struct("<fifi2f")
    return _struct_fifi2f
