// Generated by gencpp from file robotnik_msgs/LoggerQueryRequest.msg
// DO NOT EDIT!


#ifndef ROBOTNIK_MSGS_MESSAGE_LOGGERQUERYREQUEST_H
#define ROBOTNIK_MSGS_MESSAGE_LOGGERQUERYREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <robotnik_msgs/Logger.h>

namespace robotnik_msgs
{
template <class ContainerAllocator>
struct LoggerQueryRequest_
{
  typedef LoggerQueryRequest_<ContainerAllocator> Type;

  LoggerQueryRequest_()
    : query()
    , max_records(0)  {
    }
  LoggerQueryRequest_(const ContainerAllocator& _alloc)
    : query(_alloc)
    , max_records(0)  {
  (void)_alloc;
    }



   typedef  ::robotnik_msgs::Logger_<ContainerAllocator>  _query_type;
  _query_type query;

   typedef int32_t _max_records_type;
  _max_records_type max_records;





  typedef boost::shared_ptr< ::robotnik_msgs::LoggerQueryRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotnik_msgs::LoggerQueryRequest_<ContainerAllocator> const> ConstPtr;

}; // struct LoggerQueryRequest_

typedef ::robotnik_msgs::LoggerQueryRequest_<std::allocator<void> > LoggerQueryRequest;

typedef boost::shared_ptr< ::robotnik_msgs::LoggerQueryRequest > LoggerQueryRequestPtr;
typedef boost::shared_ptr< ::robotnik_msgs::LoggerQueryRequest const> LoggerQueryRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotnik_msgs::LoggerQueryRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotnik_msgs::LoggerQueryRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robotnik_msgs::LoggerQueryRequest_<ContainerAllocator1> & lhs, const ::robotnik_msgs::LoggerQueryRequest_<ContainerAllocator2> & rhs)
{
  return lhs.query == rhs.query &&
    lhs.max_records == rhs.max_records;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robotnik_msgs::LoggerQueryRequest_<ContainerAllocator1> & lhs, const ::robotnik_msgs::LoggerQueryRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robotnik_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robotnik_msgs::LoggerQueryRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotnik_msgs::LoggerQueryRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotnik_msgs::LoggerQueryRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotnik_msgs::LoggerQueryRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotnik_msgs::LoggerQueryRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotnik_msgs::LoggerQueryRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotnik_msgs::LoggerQueryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "513c0e1ab0f24516bc79aea9c7adc2e4";
  }

  static const char* value(const ::robotnik_msgs::LoggerQueryRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x513c0e1ab0f24516ULL;
  static const uint64_t static_value2 = 0xbc79aea9c7adc2e4ULL;
};

template<class ContainerAllocator>
struct DataType< ::robotnik_msgs::LoggerQueryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotnik_msgs/LoggerQueryRequest";
  }

  static const char* value(const ::robotnik_msgs::LoggerQueryRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotnik_msgs::LoggerQueryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Logger query\n"
"int32 max_records\n"
"\n"
"================================================================================\n"
"MSG: robotnik_msgs/Logger\n"
"string LOG_LEVEL_INFO=INFO\n"
"string LOG_LEVEL_WARNING=WARNING\n"
"string LOG_LEVEL_ERROR=ERROR\n"
"string LOG_LEVEL_DEBUG=DEBUG\n"
"string LOG_LEVEL_USER=USER\n"
"string robot_id\n"
"string date_time\n"
"string component\n"
"string tag\n"
"string log_level\n"
"string description\n"
;
  }

  static const char* value(const ::robotnik_msgs::LoggerQueryRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotnik_msgs::LoggerQueryRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.query);
      stream.next(m.max_records);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LoggerQueryRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotnik_msgs::LoggerQueryRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotnik_msgs::LoggerQueryRequest_<ContainerAllocator>& v)
  {
    s << indent << "query: ";
    s << std::endl;
    Printer< ::robotnik_msgs::Logger_<ContainerAllocator> >::stream(s, indent + "  ", v.query);
    s << indent << "max_records: ";
    Printer<int32_t>::stream(s, indent + "  ", v.max_records);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTNIK_MSGS_MESSAGE_LOGGERQUERYREQUEST_H
