// Generated by gencpp from file robotnik_msgs/LoggerQuery.msg
// DO NOT EDIT!


#ifndef ROBOTNIK_MSGS_MESSAGE_LOGGERQUERY_H
#define ROBOTNIK_MSGS_MESSAGE_LOGGERQUERY_H

#include <ros/service_traits.h>


#include <robotnik_msgs/LoggerQueryRequest.h>
#include <robotnik_msgs/LoggerQueryResponse.h>


namespace robotnik_msgs
{

struct LoggerQuery
{

typedef LoggerQueryRequest Request;
typedef LoggerQueryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LoggerQuery
} // namespace robotnik_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotnik_msgs::LoggerQuery > {
  static const char* value()
  {
    return "9866c376d3d7b158d2eeafc9ef42a380";
  }

  static const char* value(const ::robotnik_msgs::LoggerQuery&) { return value(); }
};

template<>
struct DataType< ::robotnik_msgs::LoggerQuery > {
  static const char* value()
  {
    return "robotnik_msgs/LoggerQuery";
  }

  static const char* value(const ::robotnik_msgs::LoggerQuery&) { return value(); }
};


// service_traits::MD5Sum< ::robotnik_msgs::LoggerQueryRequest> should match
// service_traits::MD5Sum< ::robotnik_msgs::LoggerQuery >
template<>
struct MD5Sum< ::robotnik_msgs::LoggerQueryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotnik_msgs::LoggerQuery >::value();
  }
  static const char* value(const ::robotnik_msgs::LoggerQueryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotnik_msgs::LoggerQueryRequest> should match
// service_traits::DataType< ::robotnik_msgs::LoggerQuery >
template<>
struct DataType< ::robotnik_msgs::LoggerQueryRequest>
{
  static const char* value()
  {
    return DataType< ::robotnik_msgs::LoggerQuery >::value();
  }
  static const char* value(const ::robotnik_msgs::LoggerQueryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotnik_msgs::LoggerQueryResponse> should match
// service_traits::MD5Sum< ::robotnik_msgs::LoggerQuery >
template<>
struct MD5Sum< ::robotnik_msgs::LoggerQueryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotnik_msgs::LoggerQuery >::value();
  }
  static const char* value(const ::robotnik_msgs::LoggerQueryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotnik_msgs::LoggerQueryResponse> should match
// service_traits::DataType< ::robotnik_msgs::LoggerQuery >
template<>
struct DataType< ::robotnik_msgs::LoggerQueryResponse>
{
  static const char* value()
  {
    return DataType< ::robotnik_msgs::LoggerQuery >::value();
  }
  static const char* value(const ::robotnik_msgs::LoggerQueryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTNIK_MSGS_MESSAGE_LOGGERQUERY_H
