// Generated by gencpp from file robotnik_msgs/Record.msg
// DO NOT EDIT!


#ifndef ROBOTNIK_MSGS_MESSAGE_RECORD_H
#define ROBOTNIK_MSGS_MESSAGE_RECORD_H

#include <ros/service_traits.h>


#include <robotnik_msgs/RecordRequest.h>
#include <robotnik_msgs/RecordResponse.h>


namespace robotnik_msgs
{

struct Record
{

typedef RecordRequest Request;
typedef RecordResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Record
} // namespace robotnik_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotnik_msgs::Record > {
  static const char* value()
  {
    return "b11ee07783432b9ca77edb829c7a5a8d";
  }

  static const char* value(const ::robotnik_msgs::Record&) { return value(); }
};

template<>
struct DataType< ::robotnik_msgs::Record > {
  static const char* value()
  {
    return "robotnik_msgs/Record";
  }

  static const char* value(const ::robotnik_msgs::Record&) { return value(); }
};


// service_traits::MD5Sum< ::robotnik_msgs::RecordRequest> should match
// service_traits::MD5Sum< ::robotnik_msgs::Record >
template<>
struct MD5Sum< ::robotnik_msgs::RecordRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotnik_msgs::Record >::value();
  }
  static const char* value(const ::robotnik_msgs::RecordRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotnik_msgs::RecordRequest> should match
// service_traits::DataType< ::robotnik_msgs::Record >
template<>
struct DataType< ::robotnik_msgs::RecordRequest>
{
  static const char* value()
  {
    return DataType< ::robotnik_msgs::Record >::value();
  }
  static const char* value(const ::robotnik_msgs::RecordRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotnik_msgs::RecordResponse> should match
// service_traits::MD5Sum< ::robotnik_msgs::Record >
template<>
struct MD5Sum< ::robotnik_msgs::RecordResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotnik_msgs::Record >::value();
  }
  static const char* value(const ::robotnik_msgs::RecordResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotnik_msgs::RecordResponse> should match
// service_traits::DataType< ::robotnik_msgs::Record >
template<>
struct DataType< ::robotnik_msgs::RecordResponse>
{
  static const char* value()
  {
    return DataType< ::robotnik_msgs::Record >::value();
  }
  static const char* value(const ::robotnik_msgs::RecordResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTNIK_MSGS_MESSAGE_RECORD_H
