// Generated by gencpp from file robotnik_msgs/RecordStatus.msg
// DO NOT EDIT!


#ifndef ROBOTNIK_MSGS_MESSAGE_RECORDSTATUS_H
#define ROBOTNIK_MSGS_MESSAGE_RECORDSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotnik_msgs
{
template <class ContainerAllocator>
struct RecordStatus_
{
  typedef RecordStatus_<ContainerAllocator> Type;

  RecordStatus_()
    : recording(false)
    , recording_time(0)
    , state_description()  {
    }
  RecordStatus_(const ContainerAllocator& _alloc)
    : recording(false)
    , recording_time(0)
    , state_description(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _recording_type;
  _recording_type recording;

   typedef int32_t _recording_time_type;
  _recording_time_type recording_time;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _state_description_type;
  _state_description_type state_description;





  typedef boost::shared_ptr< ::robotnik_msgs::RecordStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotnik_msgs::RecordStatus_<ContainerAllocator> const> ConstPtr;

}; // struct RecordStatus_

typedef ::robotnik_msgs::RecordStatus_<std::allocator<void> > RecordStatus;

typedef boost::shared_ptr< ::robotnik_msgs::RecordStatus > RecordStatusPtr;
typedef boost::shared_ptr< ::robotnik_msgs::RecordStatus const> RecordStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotnik_msgs::RecordStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotnik_msgs::RecordStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robotnik_msgs::RecordStatus_<ContainerAllocator1> & lhs, const ::robotnik_msgs::RecordStatus_<ContainerAllocator2> & rhs)
{
  return lhs.recording == rhs.recording &&
    lhs.recording_time == rhs.recording_time &&
    lhs.state_description == rhs.state_description;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robotnik_msgs::RecordStatus_<ContainerAllocator1> & lhs, const ::robotnik_msgs::RecordStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robotnik_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robotnik_msgs::RecordStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotnik_msgs::RecordStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotnik_msgs::RecordStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotnik_msgs::RecordStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotnik_msgs::RecordStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotnik_msgs::RecordStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotnik_msgs::RecordStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "536d9648c6be2c09d55b8554e09a4f2c";
  }

  static const char* value(const ::robotnik_msgs::RecordStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x536d9648c6be2c09ULL;
  static const uint64_t static_value2 = 0xd55b8554e09a4f2cULL;
};

template<class ContainerAllocator>
struct DataType< ::robotnik_msgs::RecordStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotnik_msgs/RecordStatus";
  }

  static const char* value(const ::robotnik_msgs::RecordStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotnik_msgs::RecordStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool recording\n"
"int32 recording_time\n"
"string state_description\n"
;
  }

  static const char* value(const ::robotnik_msgs::RecordStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotnik_msgs::RecordStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.recording);
      stream.next(m.recording_time);
      stream.next(m.state_description);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RecordStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotnik_msgs::RecordStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotnik_msgs::RecordStatus_<ContainerAllocator>& v)
  {
    s << indent << "recording: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.recording);
    s << indent << "recording_time: ";
    Printer<int32_t>::stream(s, indent + "  ", v.recording_time);
    s << indent << "state_description: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.state_description);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTNIK_MSGS_MESSAGE_RECORDSTATUS_H
