// Generated by gencpp from file robotnik_msgs/set_modbus_register_bit.msg
// DO NOT EDIT!


#ifndef ROBOTNIK_MSGS_MESSAGE_SET_MODBUS_REGISTER_BIT_H
#define ROBOTNIK_MSGS_MESSAGE_SET_MODBUS_REGISTER_BIT_H

#include <ros/service_traits.h>


#include <robotnik_msgs/set_modbus_register_bitRequest.h>
#include <robotnik_msgs/set_modbus_register_bitResponse.h>


namespace robotnik_msgs
{

struct set_modbus_register_bit
{

typedef set_modbus_register_bitRequest Request;
typedef set_modbus_register_bitResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_modbus_register_bit
} // namespace robotnik_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotnik_msgs::set_modbus_register_bit > {
  static const char* value()
  {
    return "69640e6c2ff2509eb8d9047b1c2b68df";
  }

  static const char* value(const ::robotnik_msgs::set_modbus_register_bit&) { return value(); }
};

template<>
struct DataType< ::robotnik_msgs::set_modbus_register_bit > {
  static const char* value()
  {
    return "robotnik_msgs/set_modbus_register_bit";
  }

  static const char* value(const ::robotnik_msgs::set_modbus_register_bit&) { return value(); }
};


// service_traits::MD5Sum< ::robotnik_msgs::set_modbus_register_bitRequest> should match
// service_traits::MD5Sum< ::robotnik_msgs::set_modbus_register_bit >
template<>
struct MD5Sum< ::robotnik_msgs::set_modbus_register_bitRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotnik_msgs::set_modbus_register_bit >::value();
  }
  static const char* value(const ::robotnik_msgs::set_modbus_register_bitRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotnik_msgs::set_modbus_register_bitRequest> should match
// service_traits::DataType< ::robotnik_msgs::set_modbus_register_bit >
template<>
struct DataType< ::robotnik_msgs::set_modbus_register_bitRequest>
{
  static const char* value()
  {
    return DataType< ::robotnik_msgs::set_modbus_register_bit >::value();
  }
  static const char* value(const ::robotnik_msgs::set_modbus_register_bitRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotnik_msgs::set_modbus_register_bitResponse> should match
// service_traits::MD5Sum< ::robotnik_msgs::set_modbus_register_bit >
template<>
struct MD5Sum< ::robotnik_msgs::set_modbus_register_bitResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotnik_msgs::set_modbus_register_bit >::value();
  }
  static const char* value(const ::robotnik_msgs::set_modbus_register_bitResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotnik_msgs::set_modbus_register_bitResponse> should match
// service_traits::DataType< ::robotnik_msgs::set_modbus_register_bit >
template<>
struct DataType< ::robotnik_msgs::set_modbus_register_bitResponse>
{
  static const char* value()
  {
    return DataType< ::robotnik_msgs::set_modbus_register_bit >::value();
  }
  static const char* value(const ::robotnik_msgs::set_modbus_register_bitResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTNIK_MSGS_MESSAGE_SET_MODBUS_REGISTER_BIT_H
